version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adl_app
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    environment:
      - DB_HOST=db
      - DB_DATABASE=adl_db
      - DB_USERNAME=user
      - DB_PASSWORD=user_password
    networks:
      - laravel_network

  db:
    image: mysql:9.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - 3307:3306
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge